; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:rpipico2w]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w
framework = arduino
board_build.filesystem_size = 64k
lib_deps =
	mikalhart/TinyGPSPlus @ ^1.1.0
    milesburton/DallasTemperature
    paulstoffregen/OneWire

monitor_speed = 115200
monitor_port = /dev/ttyACM0